set echo off
set feedback off
set linesize 100
set pagesize 0
set sqlprompt ''
set trimspool on
SPOOL genned_sequences.sql;
-- Write the Sequence DROP statements
SELECT 'DROP SEQUENCE DISTRESS_SEQ;' FROM DUAL;
-- configuration classes
SELECT 'DROP SEQUENCE PICKLIST_ID_SEQ;' FROM DUAL;
-- most mnroad classes
SELECT 'DROP SEQUENCE MNROAD_ID_SEQ;' FROM DUAL;
-- sensor classes
SELECT 'DROP SEQUENCE SENSOR_SEQ;' FROM DUAL;
-- jSecurity classes
SELECT 'DROP SEQUENCE JSEC_ID_SEQ;' FROM DUAL;
--
-- Write the Sequence CREATE statements
-- distress classes
SELECT 'CREATE SEQUENCE DISTRESS_SEQ MINVALUE 1 START WITH ' || MNR.DISTRESS_SEQ.NEXTVAL || ' INCREMENT BY 1 CACHE 20;' FROM DUAL;
-- configuration classes
SELECT 'CREATE SEQUENCE PICKLIST_ID_SEQ MINVALUE 1 START WITH ' || MNR.PICKLIST_ID_SEQ.NEXTVAL || ' INCREMENT BY 1 CACHE 20;' FROM DUAL;
-- most mnroad classes
SELECT 'CREATE SEQUENCE MNROAD_ID_SEQ MINVALUE 1 START WITH ' || MNR.MNROAD_ID_SEQ.NEXTVAL || ' INCREMENT BY 1 CACHE 20;' FROM DUAL;
-- sensor classes
SELECT 'CREATE SEQUENCE SENSOR_SEQ MINVALUE 1 START WITH ' || MNR.SENSOR_SEQ.NEXTVAL || ' INCREMENT BY 1 CACHE 20;' FROM DUAL;
-- jSecurity classes
SELECT 'CREATE SEQUENCE JSEC_ID_SEQ MINVALUE 1 START WITH ' || MNR.JSEC_ID_SEQ.NEXTVAL || ' INCREMENT BY 1 CACHE 20;' FROM DUAL;

SELECT 'EXIT;' FROM DUAL;
SPOOL OFF;
exit;
