rem sqlplus sys/admin@localhost/XE as sysdba @drop_pat_xe.sql
sqlplus sys/admin@localhost/XE as sysdba @create_mnru.sql
                                             
imp 'mnr/mnr@localhost/XE as sysdba' tables=(APP_CONFIG,CELL,CELL_CELL,FACILITY,JSEC_ROLE_PERMISSION_REL,JSEC_USER_PERMISSION_REL,JSEC_PERMISSION,JSEC_USER_ROLE_REL,JSEC_USER,JSEC_ROLE,LANE,LAYER,MATERIAL,ROAD_SECTION,SENSOR,              SENSOR_EVALUATION,SENSOR_MODEL,TRANSVERSE_JOINT) fromuser=mnr FILE=MnRoadCells.dmp
imp 'mnr/mnr@localhost/XE as sysdba' tables=(DISTRESS_AC, DISTRESS_AGG_SURVEY_SEMI, DISTRESS_ALPS_RESULTS_RUT, DISTRESS_CIRCULR_TEXTR_METER, DISTRESS_CUPPING, DISTRESS_FRICTION_DFT, DISTRESS_FRICTION_TRAILER, DISTRESS_JPCC, DISTRESS_LANE_SHOULDER_DROPOFF, DISTRESS_LIGHTWEIGHT_DEFLECT, DISTRESS_NUCLEAR_DENSITY, DISTRESS_OBSI_DATA, DISTRESS_OBSI_SUMMARY, DISTRESS_PCC_FAULTS, DISTRESS_PERMEABILITY_DIRECT, DISTRESS_RIDE_LISA, DISTRESS_RIDE_PATHWAYS, DISTRESS_RIDE_PAVETECH, DISTRESS_RUTTING_DIPSTICK, DISTRESS_RUTTING_STRAIGHT_EDGE, DISTRESS_SAND_PATCH, DISTRESS_SCHMIDT_HAMMER, DISTRESS_SOUND_ABSORPTION, DISTRESS_WATER_PERMEABILITY) fromuser=mnr FILE=MnRoadDistress.dmp
imp 'mnr/mnr@localhost/XE as sysdba' tables=(MAT_BINDER_ABCD_TEST, MAT_BINDER_BBR_TEST, MAT_BINDER_CRITICAL_CRACK_TEMP, MAT_BINDER_DENT_FRACTURE, MAT_BINDER_DILATOMETR_TST, MAT_BINDER_DSR_TESTS, MAT_BINDER_DT_TEST, MAT_BINDER_FATIGUE, MAT_BINDER_REPEATED_CREEP, MAT_BINDER_STRAIN_SWEEPS, MAT_BINDER_TRAD_TESTS, MAT_CONC_AIR_VOID_RESULTS, MAT_CONC_FIELD_RESULTS, MAT_CONC_FLEX_STRENGTH, MAT_CONC_FREEZE_THAW_RESULTS, MAT_CONC_MIX_GRAD_RESULTS, MAT_CONC_MOD_POISSON_RESULTS, MAT_CONC_RAPID_CHLORIDE, MAT_CONC_STRENGTH_RESULTS, MAT_CONC_THERMAL_EXPANSION, MAT_CONCRETE_MIX_DESIGNS, MAT_CORE_LENGTHS, MAT_HMA_AGING, MAT_HMA_APA, MAT_HMA_BBR_TEST, MAT_HMA_COMPLEX_SHEAR_MODU, MAT_HMA_CORE_TESTS, MAT_HMA_DCT_TEST, MAT_HMA_DILATOMETRIC_TEST, MAT_HMA_DYNAMIC_MODULUS, MAT_HMA_FLOW_NUMBER, MAT_HMA_HAMBURG, MAT_HMA_IDT_TEST, MAT_HMA_INDIRECT_TENS_FATI, MAT_HMA_MIX_TESTS, MAT_HMA_ORIGINAL_DENSITY_AIR, MAT_HMA_REPEAT_PERM_DEFORM, MAT_HMA_REPEAT_SHEAR, MAT_HMA_SCB_TEST, MAT_HMA_SENB_TEST, MAT_HMA_SIEVE_DATA, MAT_HMA_TRIAXIAL_STATIC_CREEP, MAT_HMA_TRIAXIAL_STRENGTH, MAT_HMA_TSRST_TEST, MAT_HMA_TTI_OVERLAY, MAT_HMA_ULTRASONIC_MODULUS, MAT_PROCTOR_CURVES, MAT_SAMPLES, MAT_SOIL_TESTS, MAT_TEST_TYPES, MAT_UNBOUND_FIELD_MOISTURE, MAT_UNBOUND_GRADATIONS, MAT_UNBOUND_TUBE_SUCTION) fromuser=mnr FILE=MnRoadMatSamples.dmp

imp 'mnr/mnr@localhost/XE as sysdba' tables=(CABINET_EVENT_ACTIONS,CABINET_EVENTS,CABINET_TEMPS,CSI_INV,PC_CABINETS,SITE_ACTIVITY_LOG,SITE_CABINET,SITE_INVENTORY) fromuser=mnr FILE=MnRoadCabinets.dmp
imp 'mnr/mnr@localhost/XE as sysdba' tables=(DCP_LOCATION, DCP_VALUES) fromuser=mnr FILE=MnRoadDcp.dmp
imp 'mnr/mnr@localhost/XE as sysdba' tables=(ASBUILT_JOINTS, CELL_DOWEL_BAR_LOCATIONS, DOWEL_BAR, PCC_JOINT_LOAD_TRANSFER) fromuser=mnr FILE=MnDowels.dmp
imp 'mnr/mnr@localhost/XE as sysdba' tables=(FWD_SESSION, FWD_STATION, FWD_CALIBRATION, FWD_DROP) fromuser=mnr FILE=MnRoadFwd.dmp                                             
imp 'mnr/mnr@localhost/XE as sysdba' tables=(JOB_SETUP, JOB_RESULT) FILE=MnRoadJob.dmp

imp 'mnr/mnr@localhost/XE as sysdba' tables=(DYNAMIC_LOAD_TEST_DESCRIPTIONS,DYNAMIC_LOAD_TEST_VALUES) FROMUSER=MNR TOUSER=MNR FILE=DynaLoads.dmp

drop table MNR.CELL                      cascade constraints;
drop table MNR.CELL_CELL                 cascade constraints;
drop table MNR.FACILITY                  cascade constraints;
drop table MNR.LANE                      cascade constraints;
drop table MNR.LAYER                     cascade constraints;
drop table MNR.MATERIAL                  cascade constraints;
drop table MNR.ROAD_SECTION              cascade constraints;
drop table MNR.SENSOR                    cascade constraints;
drop table MNR.SENSOR_EVALUATION         cascade constraints;
drop table MNR.SENSOR_MODEL              cascade constraints;
drop table MNR.TRANSVERSE_JOINT          cascade constraints;
drop table MNR.JSEC_ROLE_PERMISSION_REL  cascade constraints;
drop table MNR.JSEC_USER_PERMISSION_REL  cascade constraints;
drop table MNR.JSEC_PERMISSION           cascade constraints;
drop table MNR.JSEC_USER_ROLE_REL        cascade constraints;
drop table MNR.JSEC_ROLE                 cascade constraints;
drop table MNR.JSEC_USER                 cascade constraints;

imp 'mnr/mnr@localhost/XE as sysdba' show FILE=TestSectionTracking.dmp

																				 