SELECT D.ID, D.CELL, D.DESIGN, D.CELL_TYPE, D.CONSTRUCTION_BEGAN_DATE FROM_DATE
, NVL(D.CELL_END_DATE,(SELECT unique first_value(first_layer_date) OVER (PARTITION BY CELL_under ORDER BY cell) id FROM MNR.CELL_DATES cd where id_under=D.id))-1 TO_DATE
  , START_STATION,END_STATION FROM
      (
      SELECT ID, CELL, DESIGN, CELL_TYPE
        , CONSTRUCTION_BEGAN_DATE,CONSTRUCTION_ENDED_DATE
        , CELL_END_DATE
        , START_STATION,END_STATION FROM
( SELECT
ID,
CELL,
DESIGN_NUMBER DESIGN,
CELL_TYPE ,
CONSTRUCTION_BEGAN_DATE ,
CONSTRUCTION_ENDED_DATE ,
NVL(DEMOLISHED_DATE,LEAD(CONSTRUCTION_BEGAN_DATE-1,1,NULL) OVER (PARTITION BY CELL ORDER BY CONSTRUCTION_BEGAN_DATE)) CELL_END_DATE ,
START_STATION ,
END_STATION
FROM
(
   SELECT
   ID 
   ,CELL_NUMBER CELL
   ,SUBSTR(CLASS,24) CELL_TYPE
   ,(SELECT FIRST_LAYER_DATE FROM MNR.CELLS WHERE ID=C.ID) CONSTRUCTION_BEGAN_DATE
   ,CONSTRUCTION_ENDED_DATE
   ,DEMOLISHED_DATE
   ,CASE WHEN LEAD (ID,1,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 1 
   WHEN LEAD (ID,2,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 2 
   WHEN LEAD (ID,3,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 3 
   WHEN LEAD (ID,4,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 4 
   WHEN LEAD (ID,5,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 5 ELSE 1 END DESIGN_NUMBER
   ,C.START_STATION
   ,C.END_STATION
   FROM MNR.CELL C
   ORDER BY CELL,DESIGN_NUMBER
)
)
      ) D
ORDER BY START_STATION,CELL,DESIGN

CREATE OR REPLACE VIEW CELL_DESIGN AS
-- Rows in DISTRESS_* table 
-- linked via DISTRESS_*.CELL=CELLS.CELL AND DISTRESS_*.LANE=CELLS.LANE AND CELLS.FROM_DATE<=DISTRESS_*.DAY<=CELLS.TO_DATE
-- not in DISTRESS
SELECT DV.CELL,DV.LANE,DV.DAY,DV.TIME,DV.TRIAL,DV.FREQ_HZ
FROM MNR.CELLS C JOIN MNR.LANE L ON L.CELL_ID=C.ID
JOIN MNR.DISTRESS_OBSI_DATA DV ON DV.CELL=C.CELL AND DV.LANE=L.NAME AND DV.DAY BETWEEN C.FROM_DATE AND C.TO_DATE
MINUS
SELECT DV.CELL,DV.LANE,DV.DAY,DV.TIME,DV.TRIAL,DV.FREQ_HZ
FROM MNR.CELLS C JOIN LANE L ON L.CELL_ID=C.ID
JOIN MNR.DISTRESS_OBSI_DATA DV ON DV.CELL=C.CELL AND DV.LANE=L.NAME AND DV.DAY BETWEEN C.FROM_DATE AND C.TO_DATE
JOIN MNR.DISTRESS D ON D.ID=DV.ID
ORDER BY CELL,LANE,DAY,TIME,FREQ_HZ;

SELECT D.ID, D.CELL, D.DESIGN, D.CELL_TYPE, D.CONSTRUCTION_BEGAN_DATE FROM_DATE
, NVL(D.CELL_END_DATE,(SELECT unique first_value(first_layer_date) OVER (PARTITION BY CELL_under ORDER BY cell) id FROM MNR.CELL_DATES cd where id_under=D.id))-1 TO_DATE
  , START_STATION,END_STATION FROM
      (
      SELECT ID, CELL, DESIGN, CELL_TYPE
        , CONSTRUCTION_BEGAN_DATE,CONSTRUCTION_ENDED_DATE
        , CELL_END_DATE
        , START_STATION,END_STATION FROM
( SELECT
ID,
CELL,
DESIGN_NUMBER DESIGN,
CELL_TYPE ,
CONSTRUCTION_BEGAN_DATE ,
CONSTRUCTION_ENDED_DATE ,
NVL(DEMOLISHED_DATE,LEAD(CONSTRUCTION_BEGAN_DATE-1,1,NULL) OVER (PARTITION BY CELL ORDER BY CONSTRUCTION_BEGAN_DATE)) CELL_END_DATE ,
START_STATION ,
END_STATION
FROM
(
   SELECT
   ID 
   ,CELL_NUMBER CELL
   ,SUBSTR(CLASS,24) CELL_TYPE
   ,(SELECT FIRST_LAYER_DATE FROM MNR.CELLS WHERE ID=C.ID) CONSTRUCTION_BEGAN_DATE
   ,CONSTRUCTION_ENDED_DATE
   ,DEMOLISHED_DATE
   ,CASE WHEN LEAD (ID,1,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 1 
   WHEN LEAD (ID,2,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 2 
   WHEN LEAD (ID,3,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 3 
   WHEN LEAD (ID,4,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 4 
   WHEN LEAD (ID,5,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 5 ELSE 1 END DESIGN_NUMBER
   ,C.START_STATION
   ,C.END_STATION
   FROM MNR.CELL C
   ORDER BY CELL,DESIGN_NUMBER
)
)
      ) D
ORDER BY START_STATION,CELL,DESIGN
