CREATE OR REPLACE VIEW LAYER_DATES AS
SELECT LN.ID LANE_ID,MIN(L.CONSTRUCT_START_DATE) FIRST_LAYER_DATE,MAX(L.CONSTRUCT_END_DATE) LAST_LAYER_DATE            
FROM MNR.CELL C JOIN MNR.LANE LN ON LN.CELL_ID=C.ID JOIN MNR.LAYER L ON L.LANE_ID=LN.ID
GROUP BY LN.ID
