--MAT_SAMPLES BY PAVEMENT TYPE
SELECT MS.CELL
, CTD.TYPE CELL_PAVEMENT_TYPE
, TO_CHAR(CTD.FROM_DATE,'dd-Mon-yyyy') CELL_FROM_DATE
, TO_CHAR(MS.SAMPLE_DATE,'dd-Mon-yyyy') SAMPLE_DATE
, TO_CHAR(CTD.TO_DATE,'dd-Mon-yyyy') CELL_TO_DATE
, MS.MATERIAL_GROUP
FROM MNR.MAT_SAMPLES  MS JOIN
(
SELECT CA.ID
,CA.CELL
,CA.TYPE
,CASE
WHEN CA.FROM_DATE < CB.FROM_DATE THEN CA.FROM_DATE
ELSE CB.FROM_DATE
END FROM_DATE
, NVL(CA.TO_DATE, SYSDATE) TO_DATE
FROM
(
SELECT ID, CELL, FROM_DATE, TYPE, TO_DATE FROM MNR.CELLS CS
) CA
JOIN
(SELECT C.ID
, C.CELL_NUMBER CELL
, MIN(L.CONSTRUCT_START_DATE) FROM_DATE
, NULL TYPE
, MAX(C.DEMOLISHED_DATE) TO_DATE
FROM MNR.CELL C
JOIN MNR.LANE LN ON LN.CELL_ID=C.ID
JOIN MNR.LAYER L ON L.LANE_ID=LN.ID
GROUP BY C.ID, C.CELL_NUMBER) CB
ON CA.ID=CB.ID
) CTD ON CTD.CELL=MS.CELL AND MS.SAMPLE_DATE BETWEEN CTD.FROM_DATE AND CTD.TO_DATE

-- GROUP AND COUNT BY PAVEMENT TYPE || MATERIAL_GROUP
SELECT CTD.TYPE || ' ' ||  MS.MATERIAL_GROUP PVMT_TYPE_MATERIAL_GROUP, COUNT(*)
FROM MNR.MAT_SAMPLES  MS JOIN
(
SELECT CA.ID
,CA.CELL
,CA.TYPE
,CASE
WHEN CA.FROM_DATE < CB.FROM_DATE THEN CA.FROM_DATE
ELSE CB.FROM_DATE
END FROM_DATE
, NVL(CA.TO_DATE, SYSDATE) TO_DATE
FROM
(
SELECT ID, CELL, FROM_DATE, TYPE, TO_DATE FROM MNR.CELLS CS
) CA
JOIN
(SELECT C.ID
, C.CELL_NUMBER CELL
, MIN(L.CONSTRUCT_START_DATE) FROM_DATE
, NULL TYPE
, MAX(C.DEMOLISHED_DATE) TO_DATE
FROM MNR.CELL C
JOIN MNR.LANE LN ON LN.CELL_ID=C.ID
JOIN MNR.LAYER L ON L.LANE_ID=LN.ID
GROUP BY C.ID, C.CELL_NUMBER) CB
ON CA.ID=CB.ID
) CTD ON CTD.CELL=MS.CELL AND MS.SAMPLE_DATE BETWEEN CTD.FROM_DATE AND CTD.TO_DATE
GROUP BY CTD.TYPE || ' ' ||  MS.MATERIAL_GROUP
ORDER BY CTD.TYPE || ' ' ||  MS.MATERIAL_GROUP

select unique min(MS.CELL) cell
,min(CTD.ID)
,TO_CHAR(MIN(CTD.FROM_DATE),'yyyy-mm-dd') MIN_FROM_DATE,TO_CHAR(MIN(CTD.TO_DATE),'yyyy-mm-dd') MIN_TO_DATE
,max(CTD.ID)
,TO_CHAR(MAX(CTD.FROM_DATE),'yyyy-mm-dd') MAX_FROM_DATE,TO_CHAR(MAX(CTD.TO_DATE),'yyyy-mm-dd') MAX_TO_DATE
,count(*)
FROM MNR.MAT_SAMPLES  MS JOIN
(
SELECT CA.ID
,CA.CELL
,CA.TYPE
,CASE
WHEN CA.FROM_DATE < CB.FROM_DATE THEN CA.FROM_DATE
ELSE CB.FROM_DATE
END FROM_DATE
, NVL(CA.TO_DATE, sysdate) TO_DATE
FROM
(
SELECT ID, CELL, FROM_DATE, TYPE, TO_DATE FROM MNR.CELLS CS
) CA
JOIN
(SELECT C.ID
, C.CELL_NUMBER CELL
, MIN(L.CONSTRUCT_START_DATE) FROM_DATE
, NULL TYPE
, MAX(C.DEMOLISHED_DATE) TO_DATE
FROM MNR.CELL C
JOIN MNR.LANE LN ON LN.CELL_ID=C.ID
JOIN MNR.LAYER L ON L.LANE_ID=LN.ID
GROUP BY C.ID, C.CELL_NUMBER) CB
ON CA.ID=CB.ID
) CTD ON CTD.CELL=MS.CELL AND MS.SAMPLE_DATE BETWEEN CTD.FROM_DATE AND CTD.TO_DATE
group by MS.MNROAD_ID, CTD.TYPE || ' / ' ||  MS.MATERIAL_GROUP
having count(*)>1
ORDER by cell