
CREATE OR REPLACE VIEW CELL_DATES AS
select
unique "ID",
"FROM_STATION",
"TO_STATION",
"CELL",
"FROM_DATE",
"TO_DATE",
"ID_UNDER",
"CELL_UNDER",
"CELL_UNDER_FROM_DATE",
"CELL_UNDER_TO_DATE"
from
(
   SELECT
   C.ID ID ,
   CASE WHEN (C.START_STATION) > (SELECT START_STATION FROM CELL WHERE ID=CC.CELL_ID) THEN (C.START_STATION) ELSE (SELECT START_STATION FROM CELL WHERE ID=CC.CELL_ID) END FROM_STATION ,
   CASE WHEN (C.END_STATION) < (SELECT END_STATION FROM CELL WHERE ID=CC.CELL_ID) THEN (C.END_STATION) ELSE (SELECT END_STATION FROM CELL WHERE ID=CC.CELL_ID) END TO_STATION ,
   C.CELL_NUMBER CELL ,
   CONSTRUCTION_ENDED_DATE FROM_DATE ,
   C.DEMOLISHED_DATE TO_DATE ,
   CC.CELL_ID ID_UNDER ,
   (SELECT CELL_NUMBER FROM CELL WHERE ID=CC.CELL_ID) CELL_UNDER ,
   (SELECT CONSTRUCTION_ENDED_DATE FROM CELL WHERE ID=CC.CELL_ID) CELL_UNDER_FROM_DATE ,
   (SELECT DEMOLISHED_DATE FROM CELL WHERE ID=CC.CELL_ID) CELL_UNDER_TO_DATE
   FROM CELL C JOIN CELL_CELL CC ON CC.CELL_COVERS_ID = C.ID
   union
   all
   SELECT
   CC.CELL_ID ID ,
   CASE WHEN (C.START_STATION) > (SELECT START_STATION FROM CELL WHERE ID=CC.CELL_ID) THEN (C.START_STATION) ELSE (SELECT START_STATION FROM CELL WHERE ID=CC.CELL_ID) END FROM_STATION ,
   CASE WHEN (C.END_STATION) < (SELECT END_STATION FROM CELL WHERE ID=CC.CELL_ID) THEN (C.END_STATION) ELSE (SELECT END_STATION FROM CELL WHERE ID=CC.CELL_ID) END TO_STATION ,
   (SELECT CELL_NUMBER FROM CELL WHERE ID=CC.CELL_ID) CELL ,
   (SELECT CONSTRUCTION_ENDED_DATE FROM CELL WHERE ID=CC.CELL_ID) FROM_DATE ,
   (SELECT DEMOLISHED_DATE FROM CELL WHERE ID=CC.CELL_ID) TO_DATE ,
   C.ID ID_UNDER ,
   C.CELL_NUMBER CELL_UNDER ,
   CONSTRUCTION_ENDED_DATE CELL_UNDER_FROM_DATE ,
   C.DEMOLISHED_DATE CELL_UNDER_TO_DATE
   FROM CELL C JOIN CELL_CELL CC ON CC.CELL_COVERED_BY_ID = C.ID
   union
   all
   SELECT
   C.ID,
   START_STATION FROM_STATION ,
   END_STATION TO_STATION ,
   CELL_NUMBER ,
   CONSTRUCTION_ENDED_DATE FROM_DATE ,
   DEMOLISHED_DATE TO_DATE ,
   null ID_UNDER ,
   null CELL_UNDER ,
   null CELL_UNDER_FROM_DATE ,
   null CELL_UNDER_TO_DATE
   FROM CELL C
   WHERE DEMOLISHED_DATE IS NOT NULL
   UNION
   ALL
   SELECT
   C.ID,
   START_STATION FROM_STATION ,
   END_STATION TO_STATION ,
   CELL_NUMBER ,
   CONSTRUCTION_ENDED_DATE FROM_DATE ,
   DEMOLISHED_DATE TO_DATE ,
   null ID_UNDER ,
   null CELL_UNDER ,
   null CELL_UNDER_FROM_DATE ,
   null CELL_UNDER_TO_DATE
   FROM CELL C
   WHERE DEMOLISHED_DATE IS NULL
   and id not in (select cell_id from cell_cell)
)
ORDER BY FROM_STATION,FROM_DATE

CREATE OR REPLACE VIEW CELLS AS
SELECT
CELL, ID, FROM_DATE, TO_DATE
FROM CELL_DATES
union all
SELECT UNIQUE
CELL_UNDER, ID_UNDER, CELL_UNDER_FROM_DATE FROM_DATE, FROM_DATE TO_DATE
FROM CELL_DATES
WHERE CELL_UNDER IS NOT NULL
ORDER BY CELL,FROM_DATE


CREATE OR REPLACE VIEW INTER_CELL_PERIODS AS
SELECT
CELL, FROMD+1 FROM_DATE, TOD-1 TO_DATE
FROM
(
   SELECT
   CELL,
   TO_DATE FROMD,
   LEAD(FROM_DATE,1,NULL) OVER (PARTITION BY CELL ORDER BY CELL,FROM_DATE) TOD
   FROM CELLS
)
WHERE FROMD IS NOT NULL
AND TOD IS NOT NULL


CREATE OR REPLACE VIEW CELL_STATIONS AS
select unique * from (
SELECT
C.CELL,C.ID,C.FROM_DATE,C.TO_DATE,CD.FROM_STATION,CD.TO_STATION
FROM CELLS C JOIN CELL_DATES CD ON CD.ID = C.ID
UNION
ALL
SELECT
C.CELL,C.ID,C.FROM_DATE,C.TO_DATE,CD.FROM_STATION,CD.TO_STATION
FROM CELLS C JOIN CELL_DATES CD ON CD.ID_UNDER = C.ID
) order by cell, from_station

CREATE OR REPLACE VIEW WEATHER_METRIC AS
SELECT
DAY,
HOUR,
qhr,
air_temp air_temp_deg_c,
atmos_pres atmos_pres_mbars,
precip * 2.54 precip_cm,
rel_humidity rel_humidity_pct,
solar_rad_in solar_rad_in_w_per_m_squared,
solar_rad_out solar_rad_out_w_per_m_squared,
wind_direction wind_degrees_from_north,
wind_gust max_wind_gust_m_per_sec,
wind_speed avg_wind_speed_m_per_sec,
gust_direction
FROM weather_composite

CREATE TABLE WEATHER_COMPOSITE
(
   DAY timestamp NOT NULL,
   HOUR NUMBER(2) NOT NULL,
   QHR NUMBER(2) NOT NULL,
   AIR_TEMP NUMBER(8,4),
   ATMOS_PRES NUMBER(8,4),
   PRECIP NUMBER(8,4),
   REL_HUMIDITY NUMBER(8,4),
   SOLAR_RAD_IN NUMBER(10,4),
   SOLAR_RAD_OUT NUMBER(10,4),
   WIND_DIRECTION NUMBER(8,4),
   WIND_GUST NUMBER(8,4),
   WIND_SPEED NUMBER(8,4),
   GUST_DIRECTION NUMBER(8,4)
)
;

CREATE OR REPLACE VIEW WEATHER_ENGLISH AS
SELECT
DAY,
HOUR,
qhr,
ROUND (air_temp * 9 / 5 + 32, 3) air_temp_deg_f,
ROUND (atmos_pres * .00529, 2) atmos_pres_psi,
precip precip_inches,
rel_humidity rel_humidity_pct,
ROUND (solar_rad_in * .00529, 4) sol_rad_in_btu_per_ft_sq_min,
ROUND (solar_rad_out * .00529, 4) sol_rad_out_btu_per_ft_sq_min,
wind_direction wind_degrees_from_north,
ROUND (wind_gust * 2.237, 4) max_wind_gust_mph,
ROUND (wind_speed * 2.237, 4) avg_wind_speed_mph,
gust_direction
FROM weather_composite
