SELECT VIEW_NAME,TEXT
FROM all_views
WHERE owner = 'MNR'
and VIEW_NAME in ('CELL_ON_CELL','CELL_DATES','CELLS')
ORDER BY VIEW_NAME;
--
CREATE OR REPLACE VIEW CELL_ON_CELL AS
SELECT 
CC.CELL_ID ID_UNDER
,(SELECT CELL_NUMBER FROM CELL WHERE ID = CC.CELL_ID) CELL_UNDER
,(SELECT CLASS FROM CELL WHERE ID = CC.CELL_ID) CLASS_UNDER
,(SELECT START_STATION FROM CELL WHERE ID = CC.CELL_ID) FROM_STATION_UNDER
,(SELECT END_STATION FROM CELL WHERE ID = CC.CELL_ID) TO_STATION_UNDER
,(SELECT CONSTRUCTION_ENDED_DATE FROM CELL WHERE ID = CC.CELL_ID) FROM_DATE_UNDER
,(SELECT DEMOLISHED_DATE FROM CELL WHERE ID = CC.CELL_ID) TO_DATE_UNDER
,C.ID ID_OVER
,C.CELL_NUMBER CELL_OVER
,C.CLASS CLASS_OVER
,C.START_STATION FROM_STATION_OVER
,C.END_STATION TO_STATION_OVER
,C.CONSTRUCTION_ENDED_DATE FROM_DATE_OVER
,C.DEMOLISHED_DATE TO_DATE_OVER
FROM CELL C JOIN CELL_CELL CC ON CC.CELL_COVERS_ID=C.ID
--
CREATE OR REPLACE VIEW CELL_DATES AS
SELECT UNIQUE 
ID, TYPE, FROM_STATION, TO_STATION, CELL, FROM_DATE, TO_DATE, 
ID_UNDER, TYPE_UNDER, CELL_UNDER, CELL_UNDER_FROM_DATE, CELL_UNDER_TO_DATE
FROM
(
   SELECT
   C.ID ID, 
   SUBSTR(C.CLASS,24) TYPE,
   CASE WHEN (C.START_STATION) > (SELECT START_STATION FROM CELL WHERE ID=CC.CELL_ID) THEN (C.START_STATION) ELSE (SELECT START_STATION FROM CELL WHERE ID=CC.CELL_ID) END FROM_STATION, 
   CASE WHEN (C.END_STATION) < (SELECT END_STATION FROM CELL WHERE ID=CC.CELL_ID) THEN (C.END_STATION) ELSE (SELECT END_STATION FROM CELL WHERE ID=CC.CELL_ID) END TO_STATION, 
   C.CELL_NUMBER CELL, 
   CONSTRUCTION_ENDED_DATE FROM_DATE, 
   C.DEMOLISHED_DATE TO_DATE, 
   CC.CELL_ID ID_UNDER, 
   (SELECT SUBSTR(CLASS,24) FROM CELL WHERE ID=CC.CELL_ID) TYPE_UNDER, 
   (SELECT CELL_NUMBER FROM CELL WHERE ID=CC.CELL_ID) CELL_UNDER, 
   (SELECT CONSTRUCTION_ENDED_DATE FROM CELL WHERE ID=CC.CELL_ID) CELL_UNDER_FROM_DATE, 
   (SELECT DEMOLISHED_DATE FROM CELL WHERE ID=CC.CELL_ID) CELL_UNDER_TO_DATE
   FROM CELL C JOIN CELL_CELL CC ON CC.CELL_COVERS_ID = C.ID
   UNION
   ALL
   SELECT
   CC.CELL_ID ID, 
   (SELECT SUBSTR(CLASS,24) FROM CELL WHERE ID=CC.CELL_ID) TYPE, 
   CASE WHEN (C.START_STATION) > (SELECT START_STATION FROM CELL WHERE ID=CC.CELL_ID) THEN (C.START_STATION) ELSE (SELECT START_STATION FROM CELL WHERE ID=CC.CELL_ID) END FROM_STATION, 
   CASE WHEN (C.END_STATION) < (SELECT END_STATION FROM CELL WHERE ID=CC.CELL_ID) THEN (C.END_STATION) ELSE (SELECT END_STATION FROM CELL WHERE ID=CC.CELL_ID) END TO_STATION, 
   (SELECT CELL_NUMBER FROM CELL WHERE ID=CC.CELL_ID) CELL, 
   (SELECT CONSTRUCTION_ENDED_DATE FROM CELL WHERE ID=CC.CELL_ID) FROM_DATE, 
   (SELECT DEMOLISHED_DATE FROM CELL WHERE ID=CC.CELL_ID) TO_DATE, 
   C.ID ID_UNDER, 
   SUBSTR(C.CLASS,24) TYPE_UNDER,
   C.CELL_NUMBER CELL_UNDER, 
   CONSTRUCTION_ENDED_DATE CELL_UNDER_FROM_DATE, 
   C.DEMOLISHED_DATE CELL_UNDER_TO_DATE
   FROM CELL C JOIN CELL_CELL CC ON CC.CELL_COVERED_BY_ID = C.ID
   UNION
   ALL
   SELECT
   C.ID,
   SUBSTR(C.CLASS,24) TYPE,
   START_STATION FROM_STATION, 
   END_STATION TO_STATION, 
   CELL_NUMBER, 
   CONSTRUCTION_ENDED_DATE FROM_DATE, 
   DEMOLISHED_DATE TO_DATE, 
   null ID_UNDER, 
   null TYPE_UNDER, 
   null CELL_UNDER, 
   null CELL_UNDER_FROM_DATE, 
   null CELL_UNDER_TO_DATE
   FROM CELL C
   WHERE DEMOLISHED_DATE IS NOT NULL
   UNION
   ALL
   SELECT
   C.ID,
   SUBSTR(C.CLASS,24) TYPE,
   START_STATION FROM_STATION, 
   END_STATION TO_STATION, 
   CELL_NUMBER, 
   CONSTRUCTION_ENDED_DATE FROM_DATE, 
   DEMOLISHED_DATE TO_DATE, 
   null ID_UNDER, 
   null TYPE_UNDER, 
   null CELL_UNDER, 
   null CELL_UNDER_FROM_DATE, 
   null CELL_UNDER_TO_DATE
   FROM CELL C
   WHERE DEMOLISHED_DATE IS NULL
   AND ID NOT IN (SELECT CELL_ID FROM CELL_CELL)
)
--ORDER BY FROM_STATION,FROM_DATE

CREATE OR REPLACE VIEW CELLS AS
SELECT
CELL, ID, FROM_DATE, TO_DATE, TYPE
FROM CELL_DATES
union
all
SELECT
UNIQUE CELL_UNDER, ID_UNDER, CELL_UNDER_FROM_DATE FROM_DATE, FROM_DATE TO_DATE, TYPE
FROM CELL_DATES
WHERE CELL_UNDER IS NOT NULL
--ORDER BY CELL,FROM_DATE
--
CREATE OR REPLACE VIEW CELL_DEAD_DATES AS
SELECT CELL
,ID ID_OLD_CELL
,TOID ID_NEW_CELL
,TO_DATE OLD_CELL_REMOVAL_DATE
,TOD NEW_CELL_BUILT_DATE
 FROM (
SELECT C.*
, LEAD(FROM_DATE,1,NULL) OVER (PARTITION BY CELL ORDER BY CELL,FROM_DATE) TOD
, LEAD(ID,1,NULL) OVER (PARTITION BY CELL ORDER BY CELL,FROM_DATE) TOID
 FROM CELLS C
)
 WHERE TOD <> TO_DATE
--ORDER BY CELL,FROM_DATE
--
CREATE OR REPLACE VIEW CELL_SENSORS AS
SELECT
S.ID, SM.MODEL, S.SEQ, S.STATION_FT STATION, S.OFFSET_FT OFFSET, S.SENSOR_DEPTH_IN DEPTH,
TO_CHAR(S.DATE_INSTALLED,'YYYY-MM-DD') INSTALLED, 
TO_CHAR(S.DATE_REMOVED,'YYYY-MM-DD') REMOVED, 
UC.CELL_UNDER CELL, 
SUBSTR(UC.CLASS_UNDER,24) TYPE, 
LN.NAME LANE,
M.BASIC_MATERIAL, 
UC.FROM_STATION_UNDER FR_STATION, 
UC.TO_STATION_UNDER TO_STATION, 
TO_CHAR(UC.FROM_DATE_UNDER,'YYYY-MM-DD') FR_DATE, 
TO_CHAR(UC.TO_DATE_UNDER,'YYYY-MM-DD') TO_DATE, 
'Under' POSITION, 
UC.CELL_OVER CELL_O,
SUBSTR(UC.CLASS_OVER,24) TYPE_O, 
UC.FROM_STATION_OVER FR_STATION_O, 
UC.TO_STATION_OVER TO_STATION_O, 
TO_CHAR(UC.FROM_DATE_OVER,'YYYY-MM-DD') FR_DATE_O, 
TO_CHAR(UC.TO_DATE_OVER,'YYYY-MM-DD') TO_DATE_O, 
LN.ID LANE_ID,
L.ID LAYER_ID,
M.ID MATERIAL_ID
FROM
(
   SELECT
   *
   FROM CELL_ON_CELL C
   WHERE C.CELL_OVER IN
   (
      SELECT
      (SELECT CELL_NUMBER FROM CELL WHERE ID=CELL_ID)
      FROM CELL_CELL CC JOIN CELL C ON C.ID=CC.CELL_COVERED_BY_ID
   )
)
UC JOIN LANE LN ON LN.CELL_ID=UC.ID_UNDER JOIN LAYER L ON L.LANE_ID=LN.ID JOIN SENSOR S ON S.LAYER_ID = L.ID JOIN SENSOR_MODEL SM ON S.SENSOR_MODEL_ID = SM.ID JOIN MATERIAL M ON L.MATERIAL_ID=M.ID
-- Show those within the longitudinal bounds of the cell
WHERE S.STATION_FT BETWEEN UC.FROM_STATION_OVER
AND UC.TO_STATION_OVER
UNION
ALL
-- Sensors embedded in layers built on top of Cell
SELECT
S.ID, 
SM.MODEL, 
S.SEQ, 
S.STATION_FT STATION, 
S.OFFSET_FT OFFSET, 
S.SENSOR_DEPTH_IN DEPTH, 
TO_CHAR(S.DATE_INSTALLED,'YYYY-MM-DD') INSTALLED, 
TO_CHAR(S.DATE_REMOVED,'YYYY-MM-DD') REMOVED, 
UC.CELL_OVER CELL, 
SUBSTR(UC.CLASS_OVER,24) TYPE, 
LN.NAME LANE,
M.BASIC_MATERIAL, 
UC.FROM_STATION_OVER FR_STATION, 
UC.TO_STATION_OVER TO_STATION, 
TO_CHAR(UC.FROM_DATE_OVER,'YYYY-MM-DD') FR_DATE, 
TO_CHAR(UC.TO_DATE_OVER,'YYYY-MM-DD') TO_DATE, 
'Over' POSITION, 
UC.CELL_UNDER CELL_O,
SUBSTR(UC.CLASS_UNDER,24) TYPE_O, 
UC.FROM_STATION_UNDER FR_STATION_O, 
UC.TO_STATION_UNDER TO_STATION_O, 
TO_CHAR(UC.FROM_DATE_UNDER,'YYYY-MM-DD') FR_DATE_O, 
TO_CHAR(UC.TO_DATE_UNDER,'YYYY-MM-DD') TO_DATE_O, 
LN.ID LANE_ID,
L.ID LAYER_ID,
M.ID MATERIAL_ID
FROM CELL_ON_CELL UC JOIN LANE LN ON LN.CELL_ID=UC.ID_OVER JOIN LAYER L ON L.LANE_ID=LN.ID JOIN SENSOR S ON S.LAYER_ID = L.ID JOIN SENSOR_MODEL SM ON S.SENSOR_MODEL_ID = SM.ID JOIN MATERIAL M ON L.MATERIAL_ID=M.ID
--
CREATE OR REPLACE VIEW CELL_STATIONS AS
SELECT
C.CELL,C.ID,CD.TYPE,C.FROM_DATE,C.TO_DATE,CD.FROM_STATION,CD.TO_STATION
FROM CELLS C JOIN CELL_DATES CD ON CD.ID = C.ID
UNION
ALL
SELECT
C.CELL,C.ID,CD.TYPE,C.FROM_DATE,C.TO_DATE,CD.FROM_STATION,CD.TO_STATION
FROM CELLS C JOIN CELL_DATES CD ON CD.ID_UNDER = C.ID

CREATE OR REPLACE VIEW SENSOR_LOCATION AS
SELECT
C.CELL_NUMBER CELL,
SUBSTR (C.CLASS, 24) CLASS,
SM.MODEL,
S.STATION_FT STATION,
S.OFFSET_FT OFFSET,
S.SEQ,
M.BASIC_MATERIAL,
S.SENSOR_DEPTH_IN DEPTH,
S.DATE_REMOVED,
S.ORIENTATION
FROM SENSOR S JOIN SENSOR_MODEL SM ON S.SENSOR_MODEL_ID = SM.ID JOIN LAYER L ON S.LAYER_ID = L.ID JOIN LANE LN ON L.LANE_ID = LN.ID JOIN CELL C ON LN.CELL_ID = C.ID JOIN MATERIAL M ON M.ID = L.MATERIAL_ID
ORDER BY CELL, MODEL, SEQ

CREATE OR REPLACE VIEW WEATHER_ENGLISH AS
SELECT
DAY,
HOUR,
qhr,
ROUND (air_temp * 9 / 5 + 32, 3) air_temp_deg_f,
ROUND (atmos_pres * .00529, 2) atmos_pres_psi,
precip precip_inches,
rel_humidity rel_humidity_pct,
ROUND (solar_rad_in * .00529, 4) sol_rad_in_btu_per_ft_sq_min,
ROUND (solar_rad_out * .00529, 4) sol_rad_out_btu_per_ft_sq_min,
wind_direction wind_degrees_from_north,
ROUND (wind_gust * 2.237, 4) max_wind_gust_mph,
ROUND (wind_speed * 2.237, 4) avg_wind_speed_mph,
gust_direction
FROM weather_composite

CREATE OR REPLACE VIEW WEATHER_METRIC AS
SELECT
DAY,
HOUR,
qhr,
air_temp air_temp_deg_c,
atmos_pres atmos_pres_mbars,
precip / 2.54 precip_cm,
rel_humidity rel_humidity_pct,
solar_rad_in solar_rad_in_w_per_m_squared,
solar_rad_out solar_rad_out_w_per_m_squared,
wind_direction wind_degrees_from_north,
wind_gust max_wind_gust_m_per_sec,
wind_speed avg_wind_speed_m_per_sec,
gust_direction
FROM weather_composite

CREATE OR REPLACE VIEW TC_VALUES_ALL AS
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM tc_values_1993
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM tc_values_1994
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM tc_values_1995
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM tc_values_1996
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM tc_values_1997
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM tc_values_1998
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM tc_values_1999
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM tc_values_2000
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM tc_values_2001
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM tc_values_2002
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM tc_values_2003
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM tc_values_2004
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM tc_values_2005
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM tc_values_2006
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM tc_values_2007
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM tc_values_2008
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM tc_values_2009
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM tc_values
;

CREATE OR REPLACE VIEW VW_VALUES_ALL AS
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM vw_values_1993
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM vw_values_1994
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM vw_values_1995
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM vw_values_1996
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM vw_values_1997
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM vw_values_1998
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM vw_values_1999
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM vw_values_2000
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM vw_values_2001
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM vw_values_2002
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM vw_values_2003
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM vw_values_2004
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM vw_values_2005
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM vw_values_2006
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM vw_values_2007
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM vw_values_2008
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM vw_values_2009
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM vw_values
;

CREATE OR REPLACE VIEW WM_VALUES_ALL AS
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM wm_values_1993
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM wm_values_1994
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM wm_values_1995
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM wm_values_1996
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM wm_values_1997
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM wm_values_1998
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM wm_values_1999
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM wm_values_2000
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM wm_values_2001
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM wm_values_2002
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM wm_values_2003
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM wm_values_2004
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM wm_values_2005
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM wm_values_2006
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM wm_values_2007
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM wm_values_2008
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM wm_values_2009
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM wm_values
;

CREATE OR REPLACE VIEW XV_VALUES_ALL AS
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM xv_values_1993
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM xv_values_1994
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM xv_values_1995
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM xv_values_1996
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM xv_values_1997
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM xv_values_1998
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM xv_values_1999
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM xv_values_2000
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM xv_values_2001
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM xv_values_2002
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM xv_values_2003
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM xv_values_2004
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM xv_values_2005
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM xv_values_2006
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM xv_values_2007
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM xv_values_2008
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM xv_values_2009
UNION
ALL
SELECT
DAY, cell, seq, HOUR, qhr, MINUTE, VALUE
FROM xv_values
;

SELECT CELL
  ,CELL_FROM_DATE
  ,CELL_TO_DATE
,TYPE
  ,TABLE_NAME DATA_TABLE
  ,FROM_DATE
 ,TO_DATE
FROM
(
SELECT CD.CELL, CT.FROM_DATE CELL_FROM_DATE, CD.FROM_DATE, CD.TO_DATE, CT.TO_DATE CELL_TO_DATE, TYPE, CD.TABLE_NAME FROM (
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_AC' TABLE_NAME FROM MNR.DISTRESS_AC                    GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_AGG_SURVEY_SEMI' TABLE_NAME FROM MNR.DISTRESS_AGG_SURVEY_SEMI       GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_ALPS_RESULTS_RUT' TABLE_NAME FROM MNR.DISTRESS_ALPS_RESULTS_RUT      GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_CIRCULR_TEXTR_METER' TABLE_NAME FROM MNR.DISTRESS_CIRCULR_TEXTR_METER   GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_CUPPING' TABLE_NAME FROM MNR.DISTRESS_CUPPING               GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_FRICTION_DFT' TABLE_NAME FROM MNR.DISTRESS_FRICTION_DFT          GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_FRICTION_TRAILER' TABLE_NAME FROM MNR.DISTRESS_FRICTION_TRAILER      GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_JPCC' TABLE_NAME FROM MNR.DISTRESS_JPCC                  GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_LANE_SHOULDER_DROPOFF' TABLE_NAME FROM MNR.DISTRESS_LANE_SHOULDER_DROPOFF GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_LIGHTWEIGHT_DEFLECT' TABLE_NAME FROM MNR.DISTRESS_LIGHTWEIGHT_DEFLECT   GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_NUCLEAR_DENSITY' TABLE_NAME FROM MNR.DISTRESS_NUCLEAR_DENSITY       GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_OBSI_DATA' TABLE_NAME FROM MNR.DISTRESS_OBSI_DATA             GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_OBSI_SUMMARY' TABLE_NAME FROM MNR.DISTRESS_OBSI_SUMMARY          GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_PCC_FAULTS' TABLE_NAME FROM MNR.DISTRESS_PCC_FAULTS            GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_PERMEABILITY_DIRECT' TABLE_NAME FROM MNR.DISTRESS_PERMEABILITY_DIRECT   GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_RIDE_LISA' TABLE_NAME FROM MNR.DISTRESS_RIDE_LISA             GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_RIDE_PATHWAYS' TABLE_NAME FROM MNR.DISTRESS_RIDE_PATHWAYS         GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_RIDE_PAVETECH' TABLE_NAME FROM MNR.DISTRESS_RIDE_PAVETECH         GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_RUTTING_DIPSTICK' TABLE_NAME FROM MNR.DISTRESS_RUTTING_DIPSTICK      GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_RUTTING_STRAIGHT_EDGE' TABLE_NAME FROM MNR.DISTRESS_RUTTING_STRAIGHT_EDGE GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_SAND_PATCH' TABLE_NAME FROM MNR.DISTRESS_SAND_PATCH            GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_SCHMIDT_HAMMER' TABLE_NAME FROM MNR.DISTRESS_SCHMIDT_HAMMER        GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_SOUND_ABSORPTION' TABLE_NAME FROM MNR.DISTRESS_SOUND_ABSORPTION      GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, TO_CHAR(MIN(DAY),'yyyy-mm-dd') FROM_DATE, TO_CHAR(MAX(DAY),'yyyy-mm-dd') TO_DATE,'DISTRESS_WATER_PERMEABILITY' TABLE_NAME FROM MNR.DISTRESS_WATER_PERMEABILITY    GROUP BY CELL
--ORDER BY CELL,FROM_DATE
)
CD JOIN
(
SELECT CELL, TO_CHAR(FROM_DATE,'yyyy-mm-dd') FROM_DATE, TO_CHAR(TO_DATE,'yyyy-mm-dd') TO_DATE, null TABLE_NAME, TYPE 
FROM (SELECT CELL, TYPE, MIN(FROM_DATE)-60 FROM_DATE, MAX(NVL(TO_DATE,SYSDATE)) TO_DATE 
FROM MNR.CELLS GROUP BY CELL, TYPE) 
--ORDER BY CELL,FROM_DATE
)
CT 
ON CD.CELL=CT.CELL 
AND (
(CD.FROM_DATE BETWEEN CT.FROM_DATE AND CT.TO_DATE)
OR
(CD.TO_DATE BETWEEN CT.FROM_DATE AND CT.TO_DATE)
)
--ORDER BY CELL,CELL_FROM_DATE,TABLE_NAME
)
ORDER BY TYPE
  , DATA_TABLE
  ,CELL
  ,CELL_FROM_DATE

