CREATE OR REPLACE VIEW CELL_DATES AS
SELECT
ID
, TYPE
, FROM_STATION
, TO_STATION
, CELL
, CASE WHEN LEAD (ID,1,NULL) OVER (PARTITION BY CELL ORDER BY LAST_LAYER_DATE DESC) IS NULL THEN 1
	WHEN LEAD (ID,2,NULL) OVER (PARTITION BY CELL ORDER BY LAST_LAYER_DATE DESC) IS NULL THEN 2
	WHEN LEAD (ID,3,NULL) OVER (PARTITION BY CELL ORDER BY LAST_LAYER_DATE DESC) IS NULL THEN 3
	WHEN LEAD (ID,4,NULL) OVER (PARTITION BY CELL ORDER BY LAST_LAYER_DATE DESC) IS NULL THEN 4
	WHEN LEAD (ID,5,NULL) OVER (PARTITION BY CELL ORDER BY LAST_LAYER_DATE DESC) IS NULL THEN 5 ELSE 1 END DESIGN
, FIRST_LAYER_DATE
, LAST_LAYER_DATE
, FROM_DATE
, TO_DATE
, ID_UNDER
, TYPE_UNDER
, CELL_UNDER
, CELL_UNDER_FROM_DATE
, FIRST_LAYER_UNDER_DATE
, LAST_LAYER_UNDER_DATE
, CELL_UNDER_TO_DATE
, PREV_CELL_DEMO_DATE
FROM (
SELECT
UNIQUE ID,
TYPE,
FROM_STATION,
TO_STATION,
CELL,
MIN_LAYER_DATE FIRST_LAYER_DATE,
MAX_LAYER_DATE LAST_LAYER_DATE,
FROM_DATE,
TO_DATE,
ID_UNDER,
TYPE_UNDER,
CELL_UNDER,
CELL_UNDER_FROM_DATE,
MIN(MIN_LAYER_DATE_UNDER) FIRST_LAYER_UNDER_DATE,
MAX(MAX_LAYER_DATE_UNDER) LAST_LAYER_UNDER_DATE,
CELL_UNDER_TO_DATE ,
PREV_CELL_DEMO_DATE
FROM
(
   SELECT
   UNIQUE C.ID ID,
   SUBSTR(C.CLASS,24) TYPE,
   CASE WHEN (C.START_STATION) > (SELECT START_STATION FROM MNR.CELL WHERE ID=CC.CELL_ID) THEN (C.START_STATION) ELSE (SELECT START_STATION FROM MNR.CELL WHERE ID=CC.CELL_ID) END FROM_STATION,
   CASE WHEN (C.END_STATION) < (SELECT END_STATION FROM MNR.CELL WHERE ID=CC.CELL_ID) THEN (C.END_STATION) ELSE (SELECT END_STATION FROM MNR.CELL WHERE ID=CC.CELL_ID) END TO_STATION,
   C.CELL_NUMBER CELL,
   CONSTRUCTION_ENDED_DATE FROM_DATE,
   (SELECT MIN(L1.CONSTRUCT_START_DATE) FROM MNR.CELL C1 JOIN MNR.LANE LN1 ON LN1.CELL_ID=C1.ID JOIN MNR.LAYER L1 ON L1.LANE_ID=LN1.ID WHERE C1.ID=C.ID) MIN_LAYER_DATE,
   (SELECT MAX(L1.CONSTRUCT_END_DATE) FROM MNR.CELL C1 JOIN MNR.LANE LN1 ON LN1.CELL_ID=C1.ID JOIN MNR.LAYER L1 ON L1.LANE_ID=LN1.ID WHERE C1.ID=C.ID) MAX_LAYER_DATE,
   C.DEMOLISHED_DATE TO_DATE,
   CC.CELL_ID ID_UNDER,
   (SELECT SUBSTR(CLASS,24) FROM MNR.CELL WHERE ID=CC.CELL_ID) TYPE_UNDER,
   (SELECT CELL_NUMBER FROM MNR.CELL WHERE ID=CC.CELL_ID) CELL_UNDER,
   (SELECT CONSTRUCTION_ENDED_DATE FROM MNR.CELL WHERE ID=CC.CELL_ID) CELL_UNDER_FROM_DATE,
   (SELECT MIN(L1.CONSTRUCT_START_DATE) FROM MNR.CELL C1 JOIN MNR.LANE LN1 ON LN1.CELL_ID=C1.ID JOIN MNR.LAYER L1 ON L1.LANE_ID=LN1.ID WHERE C1.ID=CC.CELL_COVERS_ID) MIN_LAYER_DATE_UNDER,
   (SELECT MAX(L1.CONSTRUCT_END_DATE) FROM MNR.CELL C1 JOIN MNR.LANE LN1 ON LN1.CELL_ID=C1.ID JOIN MNR.LAYER L1 ON L1.LANE_ID=LN1.ID WHERE C1.ID=CC.CELL_COVERS_ID) MAX_LAYER_DATE_UNDER,
   (SELECT DEMOLISHED_DATE FROM MNR.CELL WHERE ID=CC.CELL_ID) CELL_UNDER_TO_DATE ,
   LAG
   (
      DEMOLISHED_DATE,1,NULL
   )
   OVER
   (
      PARTITION BY CELL_NUMBER
      ORDER BY CELL_NUMBER,CONSTRUCTION_ENDED_DATE
   )
   PREV_CELL_DEMO_DATE
   FROM MNR.CELL C JOIN MNR.CELL_CELL CC ON CC.CELL_COVERS_ID = C.ID
   UNION
   ALL
   SELECT
   UNIQUE CC.CELL_ID ID,
   (SELECT SUBSTR(C.CLASS,24) FROM MNR.CELL C WHERE C.ID=CC.CELL_ID) TYPE,
   CASE WHEN (C.START_STATION) > (SELECT START_STATION FROM MNR.CELL WHERE ID=CC.CELL_ID) THEN (C.START_STATION) ELSE (SELECT START_STATION FROM MNR.CELL WHERE ID=CC.CELL_ID) END FROM_STATION,
   CASE WHEN (C.END_STATION) < (SELECT END_STATION FROM MNR.CELL WHERE ID=CC.CELL_ID) THEN (C.END_STATION) ELSE (SELECT END_STATION FROM MNR.CELL WHERE ID=CC.CELL_ID) END TO_STATION,
   (SELECT CELL_NUMBER FROM MNR.CELL WHERE ID=CC.CELL_ID) CELL,
   (SELECT CONSTRUCTION_ENDED_DATE FROM MNR.CELL WHERE ID=CC.CELL_ID) FROM_DATE,
   (SELECT MIN(L1.CONSTRUCT_START_DATE) FROM MNR.CELL C1 JOIN MNR.LANE LN1 ON LN1.CELL_ID=C1.ID JOIN MNR.LAYER L1 ON L1.LANE_ID=LN1.ID WHERE C1.ID=CC.CELL_ID) MIN_LAYER_DATE,
   (SELECT MAX(L1.CONSTRUCT_END_DATE) FROM MNR.CELL C1 JOIN MNR.LANE LN1 ON LN1.CELL_ID=C1.ID JOIN MNR.LAYER L1 ON L1.LANE_ID=LN1.ID WHERE C1.ID=CC.CELL_ID) MAX_LAYER_DATE,
   (SELECT DEMOLISHED_DATE FROM MNR.CELL WHERE ID=CC.CELL_ID) TO_DATE,
   C.ID ID_UNDER,
   SUBSTR(C.CLASS,24) TYPE_UNDER,
   C.CELL_NUMBER CELL_UNDER,
   C.CONSTRUCTION_ENDED_DATE CELL_UNDER_FROM_DATE,
   (SELECT MIN(L1.CONSTRUCT_START_DATE) FROM MNR.CELL C1 JOIN MNR.LANE LN1 ON LN1.CELL_ID=C1.ID JOIN MNR.LAYER L1 ON L1.LANE_ID=LN1.ID WHERE C1.ID=CC.CELL_COVERED_BY_ID) MIN_LAYER_DATE_UNDER,
   (SELECT MAX(L1.CONSTRUCT_END_DATE) FROM MNR.CELL C1 JOIN MNR.LANE LN1 ON LN1.CELL_ID=C1.ID JOIN MNR.LAYER L1 ON L1.LANE_ID=LN1.ID WHERE C1.ID=CC.CELL_COVERED_BY_ID) MAX_LAYER_DATE_UNDER,
   C.DEMOLISHED_DATE CELL_UNDER_TO_DATE ,
   LAG
   (
      DEMOLISHED_DATE,1,NULL
   )
   OVER
   (
      PARTITION BY CELL_NUMBER
      ORDER BY CELL_NUMBER,CONSTRUCTION_ENDED_DATE
   )
   PREV_CELL_DEMO_DATE
   FROM MNR.CELL C JOIN MNR.CELL_CELL CC ON CC.CELL_COVERED_BY_ID = C.ID
   UNION
   ALL
   SELECT
   UNIQUE C.ID ID,
   SUBSTR(C.CLASS,24) TYPE,
   C.START_STATION FROM_STATION,
   C.END_STATION TO_STATION,
   C.CELL_NUMBER,
   C.CONSTRUCTION_ENDED_DATE FROM_DATE,
   (SELECT MIN(L1.CONSTRUCT_START_DATE) FROM MNR.CELL C1 JOIN MNR.LANE LN1 ON LN1.CELL_ID=C1.ID JOIN MNR.LAYER L1 ON L1.LANE_ID=LN1.ID WHERE C1.ID=C.ID) MIN_LAYER_DATE,
   (SELECT MAX(L1.CONSTRUCT_END_DATE) FROM MNR.CELL C1 JOIN MNR.LANE LN1 ON LN1.CELL_ID=C1.ID JOIN MNR.LAYER L1 ON L1.LANE_ID=LN1.ID WHERE C1.ID=C.ID) MAX_LAYER_DATE,
   C.DEMOLISHED_DATE TO_DATE,
   null ID_UNDER,
   null TYPE_UNDER,
   null CELL_UNDER,
   null CELL_UNDER_FROM_DATE,
   null MIN_LAYER_DATE_UNDER,
   null MAX_LAYER_DATE_UNDER,
   null CELL_UNDER_TO_DATE ,
   LAG
   (
      DEMOLISHED_DATE,1,NULL
   )
   OVER
   (
      PARTITION BY CELL_NUMBER
      ORDER BY CELL_NUMBER,CONSTRUCTION_ENDED_DATE
   )
   PREV_CELL_DEMO_DATE
   FROM MNR.CELL C
   WHERE C.DEMOLISHED_DATE IS NOT NULL
   UNION
   ALL
   SELECT
   UNIQUE C.ID ID,
   SUBSTR(C.CLASS,24) TYPE,
   C.START_STATION FROM_STATION,
   C.END_STATION TO_STATION,
   C.CELL_NUMBER,
   C.CONSTRUCTION_ENDED_DATE FROM_DATE,
   (SELECT MIN(L1.CONSTRUCT_START_DATE) FROM MNR.CELL C1 JOIN MNR.LANE LN1 ON LN1.CELL_ID=C1.ID JOIN MNR.LAYER L1 ON L1.LANE_ID=LN1.ID WHERE C1.ID=C.ID) MIN_LAYER_DATE,
   (SELECT MAX(L1.CONSTRUCT_END_DATE) FROM MNR.CELL C1 JOIN MNR.LANE LN1 ON LN1.CELL_ID=C1.ID JOIN MNR.LAYER L1 ON L1.LANE_ID=LN1.ID WHERE C1.ID=C.ID) MAX_LAYER_DATE,
   C.DEMOLISHED_DATE TO_DATE,
   null ID_UNDER,
   null TYPE_UNDER,
   null CELL_UNDER,
   null CELL_UNDER_FROM_DATE,
   null MIN_LAYER_DATE_UNDER,
   null MAX_LAYER_DATE_UNDER,
   null CELL_UNDER_TO_DATE ,
   LAG
   (
      DEMOLISHED_DATE,1,NULL
   )
   OVER
   (
      PARTITION BY CELL_NUMBER
      ORDER BY CELL_NUMBER,CONSTRUCTION_ENDED_DATE
   )
   PREV_CELL_DEMO_DATE
   FROM MNR.CELL C
   WHERE C.DEMOLISHED_DATE IS NULL
   AND C.ID NOT IN (SELECT CELL_ID FROM MNR.CELL_CELL)
)
GROUP BY ID ,
TYPE ,
FROM_STATION ,
TO_STATION ,
CELL ,
FROM_DATE ,
MIN_LAYER_DATE ,
MAX_LAYER_DATE ,
TO_DATE ,
ID_UNDER ,
TYPE_UNDER ,
CELL_UNDER ,
CELL_UNDER_FROM_DATE ,
CELL_UNDER_TO_DATE ,
PREV_CELL_DEMO_DATE
)
ORDER BY CELL, DESIGN