CREATE OR REPLACE VIEW LANE_DATES AS
SELECT CELL,LANE,LANE_ID,FROM_DATE, 
  CASE WHEN LEAD (LD.FROM_DATE,1,NULL) OVER (PARTITION BY CELL,LANE ORDER BY FROM_DATE) IS NULL THEN TO_DATE
    ELSE LEAD (LD.FROM_DATE,1,NULL) OVER (PARTITION BY CELL,LANE ORDER BY FROM_DATE)-1
  END TO_DATE
FROM (SELECT CELL,LANE,LANE_ID,MIN(CONSTRUCT_START_DATE) FROM_DATE,NVL(DEMOLISHED_DATE,SYSDATE) TO_DATE FROM LAYERS GROUP BY CELL,LANE,LANE_ID,DEMOLISHED_DATE) LD
ORDER BY CELL,LANE,FROM_DATE