CREATE OR REPLACE VIEW DISTRESS_CELL_ALL AS
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_AC' DATA_TABLE                       FROM MNR.DISTRESS_AC                    GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_AGG_SURVEY_SEMI' DATA_TABLE          FROM MNR.DISTRESS_AGG_SURVEY_SEMI       GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_ALPS_RESULTS_RUT' DATA_TABLE         FROM MNR.DISTRESS_ALPS_RESULTS_RUT      GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_CIRCULR_TEXTR_METER' DATA_TABLE      FROM MNR.DISTRESS_CIRCULR_TEXTR_METER   GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_CUPPING' DATA_TABLE                  FROM MNR.DISTRESS_CUPPING               GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_FRICTION_DFT' DATA_TABLE             FROM MNR.DISTRESS_FRICTION_DFT          GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_FRICTION_TRAILER' DATA_TABLE         FROM MNR.DISTRESS_FRICTION_TRAILER      GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_JPCC' DATA_TABLE                     FROM MNR.DISTRESS_JPCC                  GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_LANE_SHOULDER_DROPOFF' DATA_TABLE    FROM MNR.DISTRESS_LANE_SHOULDER_DROPOFF GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_LIGHTWEIGHT_DEFLECT' DATA_TABLE      FROM MNR.DISTRESS_LIGHTWEIGHT_DEFLECT   GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_NUCLEAR_DENSITY' DATA_TABLE          FROM MNR.DISTRESS_NUCLEAR_DENSITY       GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_OBSI_DATA' DATA_TABLE                FROM MNR.DISTRESS_OBSI_DATA             GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_OBSI_SUMMARY' DATA_TABLE             FROM MNR.DISTRESS_OBSI_SUMMARY          GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_PCC_FAULTS' DATA_TABLE               FROM MNR.DISTRESS_PCC_FAULTS            GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_PERMEABILITY_DIRECT' DATA_TABLE      FROM MNR.DISTRESS_PERMEABILITY_DIRECT   GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_RIDE_LISA' DATA_TABLE                FROM MNR.DISTRESS_RIDE_LISA             GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_RIDE_PATHWAYS' DATA_TABLE            FROM MNR.DISTRESS_RIDE_PATHWAYS         GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_RIDE_PAVETECH' DATA_TABLE            FROM MNR.DISTRESS_RIDE_PAVETECH         GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_RUTTING_DIPSTICK' DATA_TABLE         FROM MNR.DISTRESS_RUTTING_DIPSTICK      GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_RUTTING_STRAIGHT_EDGE' DATA_TABLE    FROM MNR.DISTRESS_RUTTING_STRAIGHT_EDGE GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_SAND_PATCH' DATA_TABLE               FROM MNR.DISTRESS_SAND_PATCH            GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_SCHMIDT_HAMMER' DATA_TABLE           FROM MNR.DISTRESS_SCHMIDT_HAMMER        GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_SOUND_ABSORPTION' DATA_TABLE         FROM MNR.DISTRESS_SOUND_ABSORPTION      GROUP BY CELL UNION ALL
SELECT UNIQUE CELL, MIN(DAY) FROM_DATE, MAX(DAY) TO_DATE,'DISTRESS_WATER_PERMEABILITY' DATA_TABLE       FROM MNR.DISTRESS_WATER_PERMEABILITY    GROUP BY CELL
