CREATE OR REPLACE VIEW CELL_MODEL_SEQ AS 
SELECT C.CELL_NUMBER CELL, SM.MODEL, SN.* FROM MNR.CELL C JOIN MNR.LANE LN ON LN.CELL_ID=C.ID JOIN MNR.LAYER LY ON LY.LANE_ID=LN.ID JOIN MNR.SENSOR SN ON SN.LAYER_ID=LY.ID JOIN MNR.SENSOR_MODEL SM ON SN.SENSOR_MODEL_ID=SM.ID

CREATE OR REPLACE VIEW TCS_OFFSET AS
SELECT
    S.REFERENCE_CELL CELL,
    S.REFERENCE_MODEL MODEL,
    S.REFERENCE_SEQUENCE SEQ,
    S.RELATIVE_OFFSET REL_OFFSET_IN,
    S.TESTNAME TCS_TESTNAME,
    S.DATA_SET TCS_DATASET,
    S.DAY TEST_DATE,
    S.HOUR,
    S.MINUTE,
    S.SECOND,
    S.TRUCK_FWD_IND,
    S.IR_TEMP,
    (SELECT OFFSET_FT*12 OFFSET_IN 
     FROM MNR.CELL_MODEL_SEQ CMS 
     WHERE CMS.CELL=S.REFERENCE_CELL 
       AND CMS.MODEL = S.REFERENCE_MODEL 
       AND CMS.SEQ = S.REFERENCE_SEQUENCE
     ) OFFSET,            
     S.RELATIVE_OFFSET + 
    (SELECT OFFSET_FT*12 OFFSET_IN 
     FROM MNR.CELL_MODEL_SEQ CMS 
     WHERE CMS.CELL=S.REFERENCE_CELL 
       AND CMS.MODEL = S.REFERENCE_MODEL 
       AND CMS.SEQ = S.REFERENCE_SEQUENCE
       and S.RELATIVE_OFFSET <> -999 AND S.RELATIVE_OFFSET IS NOT NULL
     )           
    TIRE_OFFSET_IN 
FROM MNR.TCS_DATA_SETUP S 
WHERE REFERENCE_CELL IS NOT NULL AND REFERENCE_MODEL IS NOT NULL AND REFERENCE_SEQUENCE IS NOT NULL

SELECT 
DLTD.CELL,DLTD.TCS_TESTNAME,DLTD.TCS_DATASET,DLTD.TIRE_OFFSET_IN
,C.CELL,C.MODEL,C.SEQ,C.OFFSET SENSOR_OFFSET,C.REL_OFFSET_IN,C.TIRE_OFFSET_IN
FROM TCS_OFFSET C
JOIN MNR.DYNAMIC_LOAD_TEST_DESCRIPTIONS DLTD ON DLTD.TCS_TESTNAME = C.TCS_TESTNAME AND DLTD.TCS_DATASET=TO_CHAR(C.TCS_DATASET)
WHERE C.TRUCK_FWD_IND='F' AND OFFSET <> C.TIRE_OFFSET_IN

SELECT 
DLTD.CELL,DLTD.TCS_TESTNAME,DLTD.TCS_DATASET,DLTD.TIRE_OFFSET_IN
,C.CELL,C.MODEL,C.SEQ,C.OFFSET SENSOR_OFFSET,C.REL_OFFSET_IN,C.TIRE_OFFSET_IN
FROM TCS_OFFSET C
JOIN MNR.DYNAMIC_LOAD_TEST_DESCRIPTIONS DLTD ON DLTD.TCS_TESTNAME = C.TCS_TESTNAME AND DLTD.TCS_DATASET=TO_CHAR(C.TCS_DATASET)
WHERE C.TRUCK_FWD_IND='T' 
AND C.CELL <> DLTD.CELL
AND C.TIRE_OFFSET_IN IS NOT NULL
