CREATE OR REPLACE VIEW CELL_DESIGN AS
SELECT D.ID
  , D.CELL
  , D.DESIGN
  , D.CELL_TYPE
  , D.CONSTRUCTION_BEGAN_DATE
  , D.CONSTRUCTION_ENDED_DATE
  , NVL(D.CELL_END_DATE,(
      SELECT UNIQUE FIRST_VALUE(FIRST_LAYER_DATE) OVER (PARTITION BY CELL_UNDER ORDER BY CELL) ID FROM MNR.CELL_DATES CD WHERE ID_UNDER=D.ID)
    ) CELL_END_DATE
  , START_STATION
  , END_STATION
  FROM (SELECT ID
      , CELL
      , DESIGN
      , CELL_TYPE
      , CONSTRUCTION_BEGAN_DATE
      , CONSTRUCTION_ENDED_DATE
      , CELL_END_DATE
      , START_STATION
      , END_STATION
      FROM (SELECT
      ID,
      CELL,
      DESIGN_NUMBER DESIGN,
      CELL_TYPE ,
      CONSTRUCTION_BEGAN_DATE ,
      CONSTRUCTION_ENDED_DATE ,
      NVL(DEMOLISHED_DATE,LEAD(CONSTRUCTION_BEGAN_DATE-1,1,NULL) OVER (PARTITION BY CELL ORDER BY CONSTRUCTION_BEGAN_DATE)) CELL_END_DATE ,
      START_STATION ,
      END_STATION
      FROM (SELECT
        ID
        ,CELL_NUMBER CELL
        ,SUBSTR(CLASS,24) CELL_TYPE
        ,(SELECT FIRST_LAYER_DATE FROM MNR.CELLS WHERE ID=C.ID) CONSTRUCTION_BEGAN_DATE
        ,CONSTRUCTION_ENDED_DATE
        ,DEMOLISHED_DATE
        ,CASE WHEN LEAD (ID,1,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 1
          WHEN LEAD (ID,2,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 2
          WHEN LEAD (ID,3,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 3
          WHEN LEAD (ID,4,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 4
          WHEN LEAD (ID,5,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 5 ELSE 1 
		END DESIGN_NUMBER
        ,C.START_STATION
        ,C.END_STATION
        FROM MNR.CELL C
        )
      )
    ) D
ORDER BY START_STATION,CELL,DESIGN
