CREATE OR REPLACE VIEW CELL_ON_CELL AS
SELECT 
CC.CELL_ID ID_UNDER
,(SELECT CELL_NUMBER FROM CELL WHERE ID = CC.CELL_ID) CELL_UNDER
,(SELECT CLASS FROM CELL WHERE ID = CC.CELL_ID) CLASS_UNDER
,(SELECT START_STATION FROM CELL WHERE ID = CC.CELL_ID) FROM_STATION_UNDER
,(SELECT END_STATION FROM CELL WHERE ID = CC.CELL_ID) TO_STATION_UNDER
,(SELECT CONSTRUCTION_ENDED_DATE FROM CELL WHERE ID = CC.CELL_ID) FROM_DATE_UNDER
,(SELECT DEMOLISHED_DATE FROM CELL WHERE ID = CC.CELL_ID) TO_DATE_UNDER
,C.ID ID_OVER
,C.CELL_NUMBER CELL_OVER
,C.CLASS CLASS_OVER
,C.START_STATION FROM_STATION_OVER
,C.END_STATION TO_STATION_OVER
,C.CONSTRUCTION_ENDED_DATE FROM_DATE_OVER
,C.DEMOLISHED_DATE TO_DATE_OVER
FROM CELL C JOIN CELL_CELL CC ON CC.CELL_COVERS_ID=C.ID
