CREATE OR REPLACE VIEW CELLS AS
SELECT UNIQUE ID
, CELL
, FROM_DATE
, FIRST_LAYER_DATE
, LAST_LAYER_DATE
, TO_DATE
, TYPE
, PREV_CELL_DEMO_DATE
FROM
(
  SELECT
   ID
   , CELL
   , FIRST_LAYER_DATE
   , LAST_LAYER_DATE
   , FROM_DATE
   , TO_DATE
   , TYPE
   , PREV_CELL_DEMO_DATE
  FROM CELL_DATES
 union all
  SELECT UNIQUE ID_UNDER ID
   , CELL_UNDER CELL
   , FIRST_LAYER_UNDER_DATE FIRST_LAYER_DATE
   , LAST_LAYER_UNDER_DATE LAST_LAYER_DATE
   , CELL_UNDER_FROM_DATE FROM_DATE
   , CELL_UNDER_TO_DATE TO_DATE
   , TYPE_UNDER TYPE
   , PREV_CELL_DEMO_DATE
  FROM CELL_DATES
  WHERE CELL_UNDER IS NOT NULL
)


SELECT ID
, CELL
, TYPE
, FROM_DATE
, CASE 
	WHEN CS.TO_DATE IS NOT NULL THEN CS.TO_DATE
	ELSE LEAD(FIRST_LAYER_DATE,1,SYSDATE)  OVER
   		(PARTITION BY CELL ORDER BY CELL,FROM_DATE)
END TO_DATE
FROM MNR.CELLS CS

CREATE OR REPLACE VIEW CELL_TYPES AS
SELECT CELL_TYPE, CELL,MIN(FROM_DATE) FROM_DATE, MAX(TO_DATE) TO_DATE, MIN(START_STATION) START_STATION FROM (
SELECT CD.CELL, CD.DESIGN, CD.CELL_TYPE, CD.CONSTRUCTION_BEGAN_DATE FROM_DATE, NVL(CD.CELL_END_DATE,SYSDATE) TO_DATE,START_STATION,END_STATION
FROM MNR.CELL_DESIGN CD 
ORDER BY CD.CELL, CD.CELL_TYPE, CD.START_STATION
)
GROUP BY CELL_TYPE, CELL
ORDER BY START_STATION, CELL
