CREATE OR REPLACE VIEW DISTRESS_CELL AS
SELECT CELL,CELL_FROM_DATE,CELL_TO_DATE,TYPE,DATA_TABLE,FROM_DATE,TO_DATE
FROM
(
SELECT CD.CELL, CT.FROM_DATE CELL_FROM_DATE, CD.FROM_DATE, CD.TO_DATE, CT.TO_DATE CELL_TO_DATE, TYPE, CD.DATA_TABLE FROM (
  SELECT * FROM DISTRESS_CELL_ALL
--ORDER BY CELL,FROM_DATE
) CD
JOIN
(
SELECT CELL, FROM_DATE, TO_DATE, null DATA_TABLE, TYPE 
FROM (SELECT CELL, TYPE, MIN(FROM_DATE)-30 FROM_DATE, MAX(NVL(TO_DATE,SYSDATE)) TO_DATE 
FROM CELLS GROUP BY CELL, TYPE) 
--ORDER BY CELL,FROM_DATE
) CT ON CD.CELL=CT.CELL 
  AND (
    (CD.FROM_DATE BETWEEN CT.FROM_DATE AND CT.TO_DATE)
    OR
    (CD.TO_DATE BETWEEN CT.FROM_DATE AND CT.TO_DATE)
  )
--ORDER BY CELL,CELL_FROM_DATE,TABLE_NAME
)
--ORDER BY TYPE, DATA_TABLE,CELL,CELL_FROM_DATE

SELECT DATA_TABLE,CELL,FROM_DATE,TO_DATE FROM MNR.DISTRESS_CELL_ALL
MINUS
SELECT DATA_TABLE,CELL,FROM_DATE,TO_DATE FROM MNR.DISTRESS_CELL
ORDER BY DATA_TABLE,CELL,FROM_DATE
