CREATE OR REPLACE VIEW LANE_DESIGN AS
SELECT
CD.ID CELL_ID,
CD.CELL,
CD.DESIGN,
LN.ID LANE_ID,
TO_CHAR(CD.FIRST_LAYER_DATE,'YYYY-MM-DD') FROM_DATE,
TO_CHAR(NVL(CD.TO_DATE,SYSDATE),'YYYY-MM-DD') TO_DATE,
LN.NAME LANE
FROM MNR.CELL_DATES CD JOIN MNR.LANE LN ON LN.CELL_ID=CD.ID
